---
ID: "f48ac78b-e15d-4303-9d2e-fe0080798426"
Parent: "f6f43c8f-b2f8-47a5-956c-90558d481b56"
Template: "f6f43c8f-b2f8-47a5-956c-90558d481b56"
Path: /sitecore/templates/System/Forms/Fields/Eloqua Tracking Scripts/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200222T022302Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "856fef4d-a333-404d-8c90-124791d46b4d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210908T040912Z
    - ID: "e0eef8d0-7d20-4d80-9aa2-3a25b9a0a7a0"
      Hint: Eloqua Site Id
      Value: ######
